using System.Collections.Generic;
using WoWonder.Activities.Editor.Model;

namespace WoWonder.Activities.Editor.Tools.Sticker
{
    public class StickersUrl
    {
        ///Get your stickers from here  >>> https://chatsticker.com/
        ///Get your stickers from here  >>> https://store.line.me/

        //############################# Stickers #############################

        public static readonly List<StickersModel> StickerList = new List<StickersModel>
        {
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/001.png", Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/002.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/003.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/004.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/005.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/006.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/007.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/008.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/009.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/010.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/011.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/012.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/013.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/014.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/015.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/016.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/017.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/018.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/019.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/020.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/021.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/022.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/023.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/024.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/025.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/026.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/027.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/028.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/029.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/030.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/031.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/032.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/033.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/034.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/035.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/036.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/037.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/038.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/5c1379e1040ab12ebe4b5697/iPhone/039.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/001.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/002.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/003.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/004.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/005.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/006.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/007.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/008.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/009.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/010.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/011.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/012.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/013.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/014.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/015.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/016.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/017.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/018.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/019.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/020.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/021.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/022.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/023.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/024.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/025.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/026.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/027.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/028.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/029.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/030.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/031.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/032.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/033.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/034.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/035.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/036.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/037.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/038.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/sticonshop/v1/sticon/6620d82cf52df955bb610ddf/iPhone/039.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688558/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688559/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688562/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688563/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688564/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688568/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688570/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688571/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688578/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688575/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688576/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/68688580/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/22108/ANDROID/sticker.png", Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/22112/ANDROID/sticker.png", Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/22111/ANDROID/sticker.png", Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/13456187/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/13456184/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/13456186/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/13456188/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/13456182/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/23944390/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/23944368/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135256/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135257/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135258/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135259/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135260/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135261/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135262/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135263/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135264/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135265/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135266/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135267/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/sticker/29135268/ANDROID/sticker.png" , Type = StickersType.Sticker},
            new StickersModel() { Content = "https://stickershop.line-scdn.net/stickershop/v1/product/1041829/LINEStorePC/main.png" , Type = StickersType.Sticker},
        };
    }
}