# Tên của workflow (hiển thị trên tab Actions)
name: Build Xamarin App

# Định nghĩa sự kiện kích hoạt workflow
# Ví dụ: Chạy mỗi khi có push lên nhánh 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Định nghĩa các công việc (jobs) sẽ chạy
jobs:
  # --- Công việc build cho Android ---
  build_android:
    # Chọn hệ điều hành cho máy ảo chạy job này
    runs-on: windows-latest # Hoặc ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4 # Sử dụng action có sẵn của GitHub

      # Bước 2: Cài đặt Java (cần cho Android SDK)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # Hoặc 'temurin', 'zulu', etc.
          java-version: '11' # Chọn phiên bản JDK phù hợp với dự án Xamarin của bạn

      # Bước 3: Cài đặt .NET SDK (Nếu cần phiên bản cụ thể, nếu không máy ảo thường có sẵn)
      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '6.0.x' # Thay bằng phiên bản .NET bạn cần
      
      # *** BƯỚC THÊM VÀO: Thiết lập MSBuild ***
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2 # Kiểm tra phiên bản mới nhất nếu cần

      # Bước 4: Khôi phục các gói NuGet (Đảm bảo đúng tên file .sln)
      - name: Restore NuGet packages
        run: nuget restore "WoWonder.sln" # Giả sử đây là file solution gốc của bạn

      # Bước 5: Build dự án Android
      # *** SỬA LẠI ĐƯỜNG DẪN VÀ CHỌN MỘT TARGET ***
      - name: Build Android project
        # Đường dẫn đúng là "Script\WoWonder\WoWonder.csproj" using backslashes
        # Chọn MỘT target, ví dụ: PackageForAndroid
        run: msbuild Script\WoWonder\WoWonder.csproj /p:Configuration=Release /t:PackageForAndroid
        # Hoặc nếu bạn ĐÃ cấu hình signing và muốn ký luôn:
        # run: msbuild Script\WoWonder\WoWonder.csproj /p:Configuration=Release /t:SignAndroidPackage
        # Hoặc nếu chỉ muốn biên dịch:
        # run: msbuild Script\WoWonder\WoWonder.csproj /p:Configuration=Release /t:Build

      # Bước 6: Upload Artifact (Đảm bảo path khớp với output của target đã chọn)
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          # Cập nhật path này cho đúng với nơi file .apk hoặc .aab được tạo ra
          # Use backslashes here as well for consistency on Windows
          path: Script\WoWonder\bin\Release\*.apk # Hoặc *.aab

