# Tên của workflow (hiển thị trên tab Actions)
name: Build Xamarin App

# Định nghĩa sự kiện kích hoạt workflow
# Ví dụ: Chạy mỗi khi có push lên nhánh 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Định nghĩa các công việc (jobs) sẽ chạy
jobs:
  # --- Công việc build cho Android ---
  build_android:
    # Chọn hệ điều hành cho máy ảo chạy job này
    runs-on: windows-latest # Hoặc ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4 # Sử dụng action có sẵn của GitHub

      # Bước 2: Cài đặt Java (cần cho Android SDK)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # Hoặc 'temurin', 'zulu', etc.
          java-version: '11' # Chọn phiên bản JDK phù hợp với dự án Xamarin của bạn

      # Bước 3: Cài đặt .NET SDK (Nếu cần phiên bản cụ thể, nếu không máy ảo thường có sẵn)
      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '6.0.x' # Thay bằng phiên bản .NET bạn cần
      
      # *** BƯỚC THÊM VÀO: Thiết lập MSBuild ***
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2 # Kiểm tra phiên bản mới nhất nếu cần

      # Bước 4: Khôi phục các gói NuGet (Đảm bảo đúng tên file .sln)
      - name: Restore NuGet packages
        run: nuget restore "WoWonder.sln" # Giả sử đây là file solution gốc của bạn

      # Debugging step: List directory structure
      - name: List directory structure
        run: |
          echo "Listing root directory:"
          ls "${{ github.workspace }}"
          echo "Listing Script directory:"
          ls "${{ github.workspace }}/Script"
          echo "Listing WoWonder directory:"
          ls "${{ github.workspace }}/Script/WoWonder"

      # Debugging step: List all files recursively to locate WoWonder.csproj
      - name: Locate WoWonder.csproj
        run: |
          echo "Listing all files recursively to locate WoWonder.csproj:"
          find "${{ github.workspace }}" -type f -name "WoWonder.csproj"

      # Bước 5: Build dự án Android
      - name: Build Android project
        # Use absolute path for msbuild based on the correct location of WoWonder.csproj
        run: msbuild /p:Configuration=Release /t:PackageForAndroid "${{ github.workspace }}/Script/WoWonder/WoWonder.csproj"

      # Bước 6: Upload Artifact (Đảm bảo path khớp với output của target đã chọn)
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          # Path relative to the workspace root
          path: Script/WoWonder/bin/Release/*.apk # Hoặc *.aab

